### ISSUE TITLE
FR FL Motors Dont work

### ISSUE THREAD

**Issue by Bewgg3** [MST-Robotics/MATE_2019#19]
In testing the FR and FL motors with I2C adress 10 do not work. The adress was changed to 14 and the issue was not fixed. I2c addresses 12 and 10 were swapped, so that FLFR was i2c 12. Problem followed i2c address 10 to ULUR board.

Communication works fine during startup i2c test, but fails during operation

Heartbeat continues even on frozen board, but status light remains solid, maybe an issue in the i2c receive code?

**Comment by JoeF140** [comment]
Was due to "shutoff with no command" code not re-enabling when a valid command was received. That code is now gone.
